make -C AnalogModem2/default
make -C ED1000/default
make -C ED1000/FuerPrototyp
make -C ED1000/V.21
make -C FernschrOhneFSG/default
make -C FernschrOhneFSG/English
make -C FernschrOhneFSG/USTTY-45
make -C FernschrTW39/default
make -C FernschrTW39/DoppelAusgabe
make -C FernschrTW39/USTTY-45
make -C Messgeraet/default
make -C SeriellUndSpeicher/default
make -C SeriellUndSpeicher/PlatVer13
make -C SeriellUndSpeicher/PlatVer13Test
make -C SeriellUndSpeicher/OhneSpeicher
make -C SeriellUndSpeicher/USTTY-45
make -C Wahlbruecke/default
