"\r\nvogel quax zwickt johnys pferd bim"
"\r\nsylvia wagt quick den jux bei pforzheim"
"\r\nprall vom whisky flog quax den jet zu bruch"
"\r\njeder wackere bayer vertilgt bequem zwo pfund kalbshaxen"
"\r\nfranz jagt im komplett verwahrlosten taxi quer durch bayern"
"\r\nbei jedem klugen wort von sokrates rief xanthippe zynisch: quatsch"
"\r\n1234567890,.:-+=/()"
"\r\nryryryryryryryryryryryryryryryryryryryryryryryryryryryryryryryr"
"\r\nr4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6r4y6"
"\r\n"